import { chromium } from "playwright";
import { writeFileSync, existsSync, mkdirSync } from "fs";
import { execSync } from "child_process";

const COOKIES_PATH = "/data/cookies.txt";
const STATE_DIR = "/data/browser-state";
const REFRESH_INTERVAL_MS = 6 * 60 * 60 * 1000; // 6 hours
const CDP_PORT = 9222;

function cookiesToNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by cookie-manager. Do not edit.",
    "",
  ];
  for (const c of cookies) {
    const domain = c.domain.startsWith(".") ? c.domain : `.${c.domain}`;
    const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry = c.expires > 0 ? Math.round(c.expires) : 0;
    lines.push(`${domain}\t${includeSubdomains}\t${c.path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`);
  }
  return lines.join("\n") + "\n";
}

async function exportCookies(context) {
  const cookies = await context.cookies("https://www.youtube.com");
  const netscape = cookiesToNetscape(cookies);
  writeFileSync(COOKIES_PATH, netscape);
  console.log(`[cookie-manager] Exported ${cookies.length} cookies to ${COOKIES_PATH}`);
}

async function isLoggedIn(context) {
  const cookies = await context.cookies("https://www.youtube.com");
  return cookies.some(
    (c) => c.name === "SID" || c.name === "SSID" || c.name === "LOGIN_INFO"
  );
}

async function refreshSession(context) {
  const page = await context.newPage();
  try {
    await page.goto("https://www.youtube.com", {
      waitUntil: "domcontentloaded",
      timeout: 30000,
    });
    await page.waitForTimeout(3000);
  } finally {
    await page.close();
  }
}

async function waitForLogin(context) {
  console.log("[cookie-manager] ====================================");
  console.log("[cookie-manager] Not logged in to YouTube.");
  console.log("[cookie-manager] Connect to the browser to log in:");
  console.log(`[cookie-manager]   1. SSH tunnel: ssh -L 9222:localhost:9222 <server>`);
  console.log(`[cookie-manager]   2. Open chrome://inspect in your Chrome`);
  console.log(`[cookie-manager]   3. Click "Configure" → add localhost:9222`);
  console.log(`[cookie-manager]   4. Open the remote tab and log into YouTube`);
  console.log("[cookie-manager] ====================================");

  while (true) {
    await new Promise((r) => setTimeout(r, 5000));
    if (await isLoggedIn(context)) {
      console.log("[cookie-manager] Login detected!");
      return;
    }
  }
}

function findChromiumPath() {
  const paths = [
    "/ms-playwright/chromium-1148/chrome-linux/chrome",
    "/ms-playwright/chromium_headless_shell-1148/chrome-linux/headless_shell",
  ];
  for (const p of paths) {
    if (existsSync(p)) return p;
  }
  // Fallback: find it
  try {
    return execSync("find /ms-playwright -name 'chrome' -type f 2>/dev/null | head -1")
      .toString().trim();
  } catch {
    return null;
  }
}

async function main() {
  if (!existsSync(STATE_DIR)) mkdirSync(STATE_DIR, { recursive: true });

  // Find Chromium binary path
  const chromePath = findChromiumPath();
  if (chromePath) {
    console.log(`[cookie-manager] Found Chromium at: ${chromePath}`);
  }

  // Launch persistent context with explicit executablePath
  const launchOpts = {
    headless: true,
    args: [
      `--remote-debugging-port=${CDP_PORT}`,
      "--remote-debugging-address=0.0.0.0",
      "--no-sandbox",
      "--disable-gpu",
      "--disable-dev-shm-usage",
    ],
    viewport: { width: 1280, height: 720 },
    locale: "en-US",
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  };
  if (chromePath) launchOpts.executablePath = chromePath;

  const browser = await chromium.launchPersistentContext(STATE_DIR, launchOpts);

  console.log(`[cookie-manager] Browser started, CDP on port ${CDP_PORT}`);

  // Verify CDP is accessible
  try {
    const res = await fetch(`http://0.0.0.0:${CDP_PORT}/json/version`);
    const data = await res.json();
    console.log(`[cookie-manager] CDP verified: ${data.Browser || "ok"}`);
  } catch (e) {
    console.log(`[cookie-manager] CDP check failed: ${e.message}`);
  }

  // Check if already logged in (persistent context from previous run)
  if (!(await isLoggedIn(browser))) {
    const page = await browser.newPage();
    await page.goto("https://accounts.google.com/ServiceLogin?service=youtube", {
      waitUntil: "domcontentloaded",
      timeout: 30000,
    });
    await waitForLogin(browser);
    await page.close();
  } else {
    console.log("[cookie-manager] Already logged in (from saved state)");
  }

  // Initial refresh & export
  await refreshSession(browser);
  await exportCookies(browser);

  // Periodic refresh
  console.log(`[cookie-manager] Refreshing every ${REFRESH_INTERVAL_MS / 3600000}h`);
  setInterval(async () => {
    try {
      console.log("[cookie-manager] Refreshing session...");
      await refreshSession(browser);
      await exportCookies(browser);
    } catch (err) {
      console.error("[cookie-manager] Refresh error:", err.message);
    }
  }, REFRESH_INTERVAL_MS);
}

main().catch((err) => {
  console.error("[cookie-manager] Fatal:", err);
  process.exit(1);
});
