name: MusicPlay
targets:
  MusicPlay:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - Sources
    info:
      path: Info.plist
      properties:
        UIBackgroundModes: [audio]
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIUserInterfaceStyle: Dark
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UILaunchScreen: {}
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSLocalNetworkUsageDescription: "Приложение требует доступ к локальной сети для связи с сервером MusicPlay."
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
          NSAllowsArbitraryLoadsForMedia: true
          NSAllowsLocalNetworking: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.musicplay.app
      DEVELOPMENT_TEAM: 6QSB7UUV7B
      CODE_SIGN_STYLE: Automatic
      MARKETING_VERSION: "1.2.3"
      CURRENT_PROJECT_VERSION: "2"
      SWIFT_VERSION: "5.10"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  MusicPlayUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - Tests/UITests
    dependencies:
      - target: MusicPlay
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.musicplay.app.uitests
      GENERATE_INFOPLIST_FILE: YES
